name: Update Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

jobs:
  update_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          cd main
          pip install -r requirements-dev.txt

      - name: Generate docs
        run: |
          cd main/docs
          make html

      - name: Clone Website Repo
        uses: actions/checkout@v3
        with:
          repository: Oxlac/MR.DM-Website
          path: website

      - name: Clear docs folder
        run: |
          rm -rf website/public/docs/*

      - name: Copy New docs to website
        run: |
          cp -r ./main/docs/_build/html/* ./website/public/docs/

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: website
          commit_message: "Update docs"
          commit_user_name: Oxlac Automation
          commit_author: Oxlac <actions@github.com>

